import type {NextPage} from 'next'
import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import {useEffect, useState} from "react";
import {useRouter} from "next/router";
import {createClient} from "../../components/matrix/client";
import { Room } from "matrix-js-sdk/src/models/room";
import {func} from "prop-types";
// Data structures
var roomList = [];
var viewingRoom = null;
var numMessagesToShow = 20;

const Messages: NextPage = () => {
  const route = useRouter()
  const [token, setToken] = useState("")
  const [userID, setUserID] = useState("")
  const [homeServer, setHomeServer] = useState("")
  useEffect(() => {
    const matrixToken = localStorage.getItem("hvxahv_matrix_token")
    const matrixUserId = localStorage.getItem("hvxahv_matrix_userid")
    const matrixHomeServer = localStorage.getItem("hvxahv_matrix_server")

    if (matrixToken == null || matrixUserId == null || matrixHomeServer == null) {
      const token = localStorage.getItem("hvxahv_login_token")
      const myHeaders = new Headers();
      myHeaders.append("Authorization", `Bearer ${token}`);

      const requestOptions = {
        method: 'GET',
        headers: myHeaders,
        redirect: 'follow'
      };

      // @ts-ignore
      fetch("http://localhost:8088/api/v1/message/access", requestOptions)
        .then(res => res.json())
        .then(res => {
          console.log(res)
          if (res.code == "401") {
            route.push("/messages/register").then(() => {
            })
          }
          localStorage.setItem("hvxahv_matrix_token", res.matrix.Token)
          localStorage.setItem("hvxahv_matrix_userid", res.matrix.UserId)
          localStorage.setItem("hvxahv_matrix_server", res.matrix.HomeServer)
          setToken(res.matrix.Token)
          setUserID(res.matrix.UserId)
          setHomeServer(res.matrix.HomeServer)
        })
        .catch(error => console.log('error', error));
    } else {
      setToken(matrixToken)
      setUserID(matrixUserId)
      setHomeServer(matrixHomeServer)
    }
  }, [homeServer, route, token, userID])

  const [roomTimeline, setRoomTimeline] = useState<any>([])
  const [joinedRooms, setJoinedRooms] = useState<any>([])
  useEffect(() => {
    if (token != "") {
      (async () => {
        const client = await createClient(token, userID)

        client.on("Room", function (e) {
          setJoinedRooms((r: any) => [...r, e]);
        })
        client.on("Room.timeline", function(event, room, toStartOfTimeline) {
          if (toStartOfTimeline) {
            return; // don't print paginated results
          }
          if (event.getType() !== "m.room.message") {
            return; // only print messages
          }
          // console.log(room)
          console.log(
            // the room name will update with m.room.name events automatically
            "(%s) %s :: %s", room.name, event.getSender(), event.getContent().body
          )
          setRoomTimeline((r: any) => [...r, room])
          console.log(event.getContent())
          // console.log(event.getSender())
          // console.log(room)
          // console.log(room.name)
        })
      })()
    }
  }, [homeServer, token, userID])

  console.log(joinedRooms)
  console.log(roomTimeline)
  return (
    <div className={styles.container}>
      <Head>
        <title>Messages</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <main className={styles.main}>

        <h1>ROOM LIST</h1>
        {joinedRooms && joinedRooms.map((i: any, idx: any) => {
          return (
            <div key={idx}>
              <div>{i.name != "Empty room" ? <div>ROOM: {i.name} - ROOM ID: {i.roomId}</div> : null}</div>
            </div>
          )
        })}
        <hr/>
        <h1>Messages</h1>
        {/*{roomTimeline && roomTimeline.reverse().map((i: any, idx: any) => {*/}
        {/*  return (*/}
        {/*    <div key={idx}>*/}
        {/*      <div>{i}</div>*/}
        {/*      <hr/>*/}
        {/*    </div>*/}
        {/*  )*/}
        {/*})}*/}
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}

export default Messages
