import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import {useEffect, useState} from "react";
import {useRouter} from "next/router";

const MessagesRegister: NextPage = () => {
  const [password, setPassword] = useState("")
  const route = useRouter()

  console.log(password)
  return (
    <div className={styles.container}>
      <Head>
        <title>Matrix Access Register</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>PLEASE ENTER YOUR PASSWORD.</h1>
        <input type="password" onChange={e => setPassword(e.target.value)}/>
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}

export default MessagesRegister
