import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import {useState} from "react";
import {useRouter} from "next/router";

const MessagesRegister: NextPage = () => {
  const [password, setPassword] = useState("")
  const route = useRouter()

  const handleRegisterMatrixAccess = () => {
    const token = localStorage.getItem("hvxahv_login_token")
    const myHeaders = new Headers();
    myHeaders.append("Authorization", `Bearer ${token}`);

    const formdata = new FormData();
    formdata.append("password", password);

    const requestOptions = {
      method: 'POST',
      headers: myHeaders,
      body: formdata,
      redirect: 'follow'
    };

    // @ts-ignore
    fetch("http://localhost:8088/api/v1/message/access", requestOptions)
      .then(res => res.json())
      .then(res => {
        console.log(res)
        if (res.code == "200") {
          route.push("/messages").then(() => {})
        }
      })
      .catch(error => console.log('error', error));
  }

  console.log(password)
  return (
    <div className={styles.container}>
      <Head>
        <title>Matrix Access Register</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>PLEASE ENTER YOUR PASSWORD.</h1>
        <input type="password" onChange={e => setPassword(e.target.value)}/>
        <button onClick={() => handleRegisterMatrixAccess()}>Start</button>
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}

export default MessagesRegister
