import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import Notifications from "../../components/notification";
import React from "react";

const IAM: NextPage = () => {

  return (
    <div className={styles.container}>
      <Head>
        <title>IAm</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Notifications/>
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}

export default IAM
