import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../../styles/Home.module.css'

const Chat: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Chat</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1>Saved List</h1>
            </main>

            <footer className={styles.footer}>

            </footer>
        </div>
    )
}

export default Chat
