import React, {useState} from 'react';
import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../../styles/Home.module.css'

const Saved: NextPage = () => {
  const [file, setFile] = useState()

  const upload = ({e}: { e: any }) => {
    setFile(e.target)
  }

  const encrypt = () => {

  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Saved</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <div>
        <input type="file" onChange={e => upload({e: e})}/>
        <button onClick={() => encrypt()}>ENCRYPT</button>
      </div>
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}

export default Saved
